/**
 * This file is auto-generated by 'configure_tenant.sh'.
 * DO NOT EDIT THIS FILE DIRECTLY. 
 * Any changes will be overwritten during the build process.
 */
module.exports = {
  TENANT_ID: "default",
  DISPLAY_NAME: "MTA Dev",
  DISPLAY_VERSION_NUMBER: "1.0.0",
  BUNDLE_ID: "com.codeductor.development",
};
