#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# ---------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------
cleanEnv=false
configureAndroid=false
configureIos=false
tenantDir="tenants/$TENANT_ID/"
productName="MultiTenantApp"

# Function to convert a string to lowercase
to_lowercase() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}

# Convert productName to lowercase
productNameLowercase=$(to_lowercase "$productName")

# ---------------------------------------------------------------------
# Process command-line options
# ---------------------------------------------------------------------
for option in "$@"; do
    case "$option" in
        android) configureAndroid=true ;;
        ios) configureIos=true ;;
        clean) cleanEnv=true ;;
        *) echo "Warning: Unknown option '$option'" ;;
    esac
done

echo -e "\nOptions"
echo -e "===================================="
echo -e "=> Tenant: $TENANT_ID"
echo -e "=> Product Name: $productName"
echo -e "=> Clean Environment: $cleanEnv"
echo -e "=> Android Setup: $configureAndroid"
echo -e "=> iOS Setup: $configureIos"
echo -e "====================================\n"

[[ ! -d $tenantDir ]] && echo "Error: Tenant not found in './tenants/' folder" && exit 1

# ---------------------------------------------------------------------
# Clean environment
# ---------------------------------------------------------------------
if [[ "$cleanEnv" == "true" ]]; then
    echo -ne "=> Cleaning environment..."
    rm -rf android ios
    rm -rf .env
    rm -rf .env.development
    rm -rf .env.production
    rm -rf tenant-config.js
    rm -rf tsconfig.json
    echo -e "Done"
fi

# ---------------------------------------------------------------------
# Configure Environment 
# Only run if either android or ios is set to true
# ---------------------------------------------------------------------
if [[ "$configureAndroid" == "true" || "$configureIos" == "true" ]]; then

    echo -e "\t=> Configuring environment..."
    
    echo -en "=> Generating tsconfig.json ..."
    npx tsconfig.js --once -- ios ios_template node_modules
    echo -e "Done"

    if [[ "$BUILD_ENV" == "production" ]]; then
        echo -en "=> Setting up for production environment..."
        cp -rf "$tenantDir.env.$TENANT_ID.production" ".env"
    else
        echo -en "=> Setting up for development environment..."
        cp -rf "$tenantDir.env.$TENANT_ID.development" ".env"
    fi

    set -a
    source .env
    set +a

    if [[ -z "$BUNDLE_ID" ]]; then
        echo -e "\aInfo: BUNDLE_ID is not set, using 'default'"
        BUNDLE_ID="default"
    fi

    if [[ -z "$DISPLAY_NAME" ]]; then
        echo -e "\aInfo: DISPLAY_NAME is not set, using 'default'"
        DISPLAY_NAME="default"
    fi

    echo -e "Done"

    # ---------------------------------------------------------------------
    # Generate tenant-config.js
    # ---------------------------------------------------------------------
    echo -ne "=> Generating tenant-config.js..."
    
cat <<EOF > tenant-config.js
/**
 * This file is auto-generated by 'configure_tenant.sh'.
 * DO NOT EDIT THIS FILE DIRECTLY. 
 * Any changes will be overwritten during the build process.
 */
module.exports = {
  TENANT_ID: "${TENANT_ID}",
  DISPLAY_NAME: "${DISPLAY_NAME}",
  DISPLAY_VERSION_NUMBER: "${DISPLAY_VERSION_NUMBER}",
  BUNDLE_ID: "${BUNDLE_ID}",
};
EOF

    echo -e "Done"
fi

# ---------------------------------------------------------------------
# Configure Android
# ---------------------------------------------------------------------
if [[ "$configureAndroid" == "true" ]]; then

    echo -e "=> Configure Android:"

    sourceDir="${tenantDir}nativeAssets/appIcon/android/"
    [[ ! -d "$sourceDir" ]] && echo "Error: $sourceDir does not exist" # && exit 1

    # ---------------------------------------------------------------------
    # Copy android_template to android
    # ---------------------------------------------------------------------
    echo -ne "\t=> Copying android_template to android..."
    cp -rf android_template android
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Set up for Java/Kotlin package folder structure
    # ---------------------------------------------------------------------
    OLD_NAMESPACE="com.${productNameLowercase}"
    NEW_NAMESPACE="${BUNDLE_ID}"
    SRC_DIR="android/app/src/main/java"
    OLD_PACKAGE_PATH=$(echo "$OLD_NAMESPACE" | sed 's/\./\//g')
    NEW_PACKAGE_PATH=$(echo "$NEW_NAMESPACE" | sed 's/\./\//g')

    # ---------------------------------------------------------------------
    # Update App Name In Strings
    # ---------------------------------------------------------------------
    echo -ne "\t=> Updating app name in strings.xml..."
    # Escape special characters for XML
    ESCAPED_DISPLAY_NAME=$(echo "$DISPLAY_NAME" | sed -e 's/&/&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' -e 's/'\''/\&apos;/g' -e 's/\"/\&quot;/g')

    # File path
    FILE_PATH="android/app/src/main/res/values/strings.xml"

    # Remove the old line and add the new one
    sed -i "" "/<string name=\"app_name\">/d" "$FILE_PATH" # Delete the line with app_name
    # This is formatted to make it render correctly in the file.
    sed -i "" "/<resources>/a\\
    <string name=\"app_name\">${ESCAPED_DISPLAY_NAME}</string>
    " "$FILE_PATH"
    
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Update Gradle namespace
    # ---------------------------------------------------------------------
    echo -ne "\t=> Updating gradle path..."
    sed -i "" "s|namespace \"com\.replace\.me\"|namespace \"${BUNDLE_ID}\"|g" \
      android/app/build.gradle
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Update MainActivity and MainApplication
    # ---------------------------------------------------------------------
    
    echo -en "\t=> Updating MainActivity and MainApplication..."
    
    sed -i "" "s|^package com\.${productNameLowercase}|package ${BUNDLE_ID}|" \
    android/app/src/main/java/com/${productNameLowercase}/MainActivity.kt

    sed -i "" "s|^package com\.${productNameLowercase}|package ${BUNDLE_ID}|" \
    android/app/src/main/java/com/${productNameLowercase}/MainApplication.kt

    echo -e "Done"

    # ---------------------------------------------------------------------
    # Move files to new package path
    # ---------------------------------------------------------------------
    mkdir -p "$SRC_DIR/$NEW_PACKAGE_PATH/"
    echo -ne "\t=> Moving $SRC_DIR/$OLD_PACKAGE_PATH to $SRC_DIR/$NEW_PACKAGE_PATH..."
    mv "$SRC_DIR/$OLD_PACKAGE_PATH/"* "$SRC_DIR/$NEW_PACKAGE_PATH/" 2>/dev/null || true
    rm -rf "$SRC_DIR/$OLD_PACKAGE_PATH"
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Apply App Icon
    # ---------------------------------------------------------------------
    echo -ne "\t=> Copying app icon from $sourceDir to android/app/src/main/res..."
    cp -rf "$sourceDir" "./android/app/src/main/"
    echo -e "Done"

fi

# ---------------------------------------------------------------------
# Configure iOS
# ---------------------------------------------------------------------
if [[ "$configureIos" == "true" ]]; then

    # ---------------------------------------------------------------------
    # Configure tenant for iOS
    # ---------------------------------------------------------------------
    echo -e "=> Configuring iOS:"
    sourceDir="${tenantDir}nativeAssets/appIcon/ios/"
    [[ ! -d "$sourceDir" ]] && echo "Error: $sourceDir does not exist" # && exit 1

    # ---------------------------------------------------------------------
    # Copy ios_template to ios
    # ---------------------------------------------------------------------
    echo -ne "\t=> Copying ios_template to ios..."
    cp -rf ios_template ios
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Apply App Icon
    # --------------------------------------------------------------------- 
    echo -en "\t=> Copying app icon from $sourceDir to ios/Runner/Assets.xcassets/AppIcon.appiconset..."
    cp -rf $sourceDir "ios/$productName/Images.xcassets/"
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Set bundle ID and app name for iOS
    # ---------------------------------------------------------------------
    /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" ios/$productName/Info.plist

    # Escape special characters for pbxproj
    ESCAPED_DISPLAY_NAME_PBXPROJ=$(echo "$DISPLAY_NAME" | sed -e 's/&/\\&/g')

    # ---------------------------------------------------------------------
    # Update keys in pbxproj file
    # ---------------------------------------------------------------------
    echo -ne "\t=> Updating pbxproj file..."
    sed -i "" "s/\(PRODUCT_BUNDLE_IDENTIFIER = \).*\(;\)/\1${BUNDLE_ID}\2/" "ios/$productName.xcodeproj/project.pbxproj"
    sed -i "" "s/\(MARKETING_VERSION = \).*\(;\)/\1${DISPLAY_VERSION_NUMBER}\2/" "ios/$productName.xcodeproj/project.pbxproj"
    sed -i "" "s/\(CURRENT_PROJECT_VERSION = \).*\(;\)/\1${BUILD_NUMBER}\2/" "ios/$productName.xcodeproj/project.pbxproj"
    sed -i "" "s/\(PRODUCT_NAME = \).*\(;\)/\1\"${ESCAPED_DISPLAY_NAME_PBXPROJ}\"\2/" "ios/$productName.xcodeproj/project.pbxproj"
    
    echo -e "Done"

    # ---------------------------------------------------------------------
    # Run pod install in ios directory
    # ---------------------------------------------------------------------
    echo -e "\t=> Running pod install in ios directory..."
    cd ios && pod install && cd ..
    echo -e "Done"

fi

echo -e "\n[Process Complete]\n"
# exit 0 # Disable during testing